### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by clarus**
* remove space before colon;
* there specification => their specification.

### CODE REVIEW

**Comment by clarus** [comment]
Hi,

Currently reading your report to get an introduction to Tezos! Thanks. Putting here some typos I have seen so far. I just arrived today at Nomadic Labs.

**Comment by clarus** [comment]
(if that's OK)

**Comment by Vertmo** [comment]
Hi ! Thanks for your corrections. I'd welcome you to Nomadic Labs, but since I'm not an employee anymore myself, I'm not sure if it would be relevant :p

**Comment by clarus** [comment]
OK, thanks!

**Pull request merged**
